site_name: toolfoundation
site_description: Documentation for toolfoundation
repo_name: jonwraymond/toolfoundation
repo_url: https://github.com/jonwraymond/toolfoundation
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Design Notes: design-notes.md
  - User Journey: user-journey.md
theme:
  name: material
